"""Add description to MeetingRoom

Revision ID: 24324f58d305
Revises: db8d0148f513
Create Date: 2022-11-20 22:16:17.578607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24324f58d305'
down_revision = 'db8d0148f513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetingroom', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetingroom', 'description')
    # ### end Alembic commands ###
