"""Add user relationship to Reservation

Revision ID: 795b1cd5b6b0
Revises: bc9f29196fa8
Create Date: 2022-11-28 23:32:29.523558

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '795b1cd5b6b0'
down_revision = 'bc9f29196fa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_reservation_user_id_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
