"""Add user model1

Revision ID: 90149dcf67a2
Revises: c63bd3ddc4da
Create Date: 2022-11-28 22:08:20.640179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90149dcf67a2'
down_revision = 'c63bd3ddc4da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
