"""Edit user model

Revision ID: bc9f29196fa8
Revises: 90149dcf67a2
Create Date: 2022-11-28 23:09:55.409093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc9f29196fa8'
down_revision = '90149dcf67a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_index('ix_oauth_account_account_id', table_name='oauth_account')
    op.drop_index('ix_oauth_account_oauth_name', table_name='oauth_account')
    op.drop_table('oauth_account')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_account',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('oauth_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('access_token', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('expires_at', sa.INTEGER(), nullable=True),
    sa.Column('refresh_token', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('account_id', sa.VARCHAR(length=320), nullable=False),
    sa.Column('account_email', sa.VARCHAR(length=320), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_oauth_account_oauth_name', 'oauth_account', ['oauth_name'], unique=False)
    op.create_index('ix_oauth_account_account_id', 'oauth_account', ['account_id'], unique=False)
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
